### ISSUE TITLE
Built-In generated books from loot have invalid tag

### ISSUE THREAD

**Issue by nicuch** [zhehedream/Oh-the-dungeon#2]
https://imgur.com/a/Z2pwsHl
Found this book as a loot in one of the generated dungeons.

**Comment by zhehedream** [comment]
looks like in 1.15 the Mojang has changed the JSON format of written books.
Right now I cannot find out any document about this format. So we need to wait for forge 1.15 so we can solve this.

**Comment by zhehedream** [comment]
[https://www.spigotmc.org/threads/1-15-invalid-book-tag.408957/](url)

should be fixed in next version
