### ISSUE TITLE
Redstone is not placed

### ISSUE THREAD

**Issue by nicuch** [zhehedream/Oh-the-dungeon#3]
https://imgur.com/a/9k9fKNV
In this image you should see a small redstone-build, where you can turn up the light of a redstone lamp. However, the redstone circuit is broken because there's no redstone placed (only the redstone torches). https://imgur.com/a/ULwcCly
I've placed myself the torch for the light.

**Comment by zhehedream** [comment]
looks like in 1.15 the Mojang has changed the JSON format of written books.
Right now I cannot find out any document about this format. So we need to wait for forge 1.15 so we can solve this.

**Comment by zhehedream** [comment]
Don't know what would cause this, some circuits won't work (like a dilapidated house). So maybe it's OK to just keep it unchanged.

If you still want a fix, feel free to reopen this ticket. I'll try to do that
