### ISSUE TITLE
1.15 blocks are not parsed correctly

### ISSUE THREAD

**Issue by nicuch** [zhehedream/Oh-the-dungeon#4]
https://imgur.com/a/aZe0xup
As you can see in the image, that stone-slab should have been spruce logs. Well... they are not xD
Sorry for all the bugs reported at once :)

**Comment by zhehedream** [comment]
Well, it means to be a stone_slab, although the block for minecraft:stone_slab has changed since 1.14...

If you still think this as a bug, feel free to reopen this
